/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package selinum.test;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.*;
import java.util.List;
import static org.testng.Assert.*;

public class AppTest {

    WebDriver webDriver;

    @Test
    public void testpetclincqpros() {

        // Check if image displayed or not
        String imgXpath="/html/body/div/div/div[1]/div/img";
        WebElement welcomeImage=webDriver.findElement(By.xpath(imgXpath));
        assertEquals(welcomeImage.isDisplayed(),true);



        // click in Veterinarians button
        String anchorXpath="//*[@id=\"main-navbar\"]/ul/li[3]/a";
        WebElement anchorTag= webDriver.findElement(By.xpath(anchorXpath));
        anchorTag.click();

        //Get all veterinarians
        List<WebElement> veteDoc=(List) webDriver.findElements(By.xpath("//*[@id=\"vets\"]/tbody/tr"));
        System.out.println(veteDoc.size());

        // Print just veterinarians name
        String fisrtXpath="//*[@id=\"vets\"]/tbody/tr[";
        String lastXpath="]/td[1]";
        String xpath;

        System.out.println("-----------------veterinarians-----------------");

        for(int i=1;i<veteDoc.size();i++){
            xpath=fisrtXpath+i+lastXpath;
            WebElement vent=webDriver.findElement(By.xpath(xpath));
            System.out.println(vent.getText());

        }




        // Find owner anchor and click on it
        WebElement findOwner=webDriver.findElement(By.xpath("//*[@id=\"main-navbar\"]/ul/li[2]/a"));
        findOwner.click();
        //Find findButton and click on it
        WebElement findBtn= webDriver.findElement(By.xpath("//*[@id=\"search-owner-form\"]/div[2]/div/button"));
        findBtn.click();

        List<WebElement> allOwner=webDriver.findElements(By.xpath("//*[@id=\"owners\"]/tbody/tr"));

        String fisrtXpath1="//*[@id=\"owners\"]/tbody/tr[";
        String lastXpath1="]/td[1]";
        String xpath1;

        System.out.println("-----------------owners-----------------");
        for(int i=1;i<allOwner.size();i++){
            xpath1=fisrtXpath1+i+lastXpath1;
            WebElement owner=webDriver.findElement(By.xpath(xpath1));
            System.out.println(owner.getText());
        }

        webDriver.navigate().back();

        //Find Add Owner and click on it
        WebElement addOwner=webDriver.findElement(By.linkText("Add Owner"));
        addOwner.click();

        String firstNmae="Khaled Mosleh";
        String lastName="Mosleh1994";
        String address="Abu-Dhabi";
        String city="Ainalbasha";
        String telephone="079555";

        //Find inputs and fill it to add new owner
        webDriver.findElement(By.name("firstName")).sendKeys(firstNmae);
        webDriver.findElement(By.name("lastName")).sendKeys(lastName);
        webDriver.findElement(By.name("address")).sendKeys(address);
        webDriver.findElement(By.name("city")).sendKeys(city);
        webDriver.findElement(By.name("telephone")).sendKeys(telephone);
        webDriver.findElement(By.xpath("//*[@id=\"add-owner-form\"]/div[2]/div/button")).click();

        //Add pit for User Added
        String pitName="momo";
        String birthpit="1994-12-18";
        String pitType="dog";

        webDriver.findElement(By.xpath("/html/body/div/div/a[2]")).click();
        webDriver.findElement(By.name("name")).sendKeys(pitName);
        webDriver.findElement(By.name("birthDate")).sendKeys(birthpit);
        WebElement select=webDriver.findElement(By.id("type"));
        Select typeOfpit=new Select(select);
        typeOfpit.selectByVisibleText(pitType);

        //Submit Form to Add pit to owner

        webDriver.findElement(By.xpath("/html/body/div/div/form/div[2]/div/button")).click();

       //get Owner info to test
        String testName=webDriver.findElement(By.xpath("/html/body/div/div/table[1]/tbody/tr[1]/td/b")).getText();
        String testAdress=webDriver.findElement(By.xpath("/html/body/div/div/table[1]/tbody/tr[2]/td")).getText();
        String testCity=webDriver.findElement(By.xpath("/html/body/div/div/table[1]/tbody/tr[3]/td")).getText();
        String testTelephone=webDriver.findElement(By.xpath("/html/body/div/div/table[1]/tbody/tr[4]/td")).getText();

       //get Pit info to tst
        String testPitame= webDriver.findElement(By.xpath("/html/body/div/div/table[2]/tbody/tr/td[1]/dl/dd[1]")).getText();
        String testPitbirth=webDriver.findElement(By.xpath("/html/body/div/div/table[2]/tbody/tr/td[1]/dl/dd[2]")).getText();
        String testType=webDriver.findElement(By.xpath("/html/body/div/div/table[2]/tbody/tr/td[1]/dl/dd[3]")).getText();

        //Test Owner Info
        String expectedName=firstNmae+" "+lastName;
        assertEquals(testName,expectedName);
        assertEquals(testAdress,address);
        assertEquals(testCity,city);
        assertEquals(testTelephone,telephone);

        //Test pit info
        assertEquals(testPitame,pitName);
        assertEquals(testPitbirth,birthpit);
        assertEquals(testType,pitType);

    }

    @BeforeClass
    public void testPit(){

        System.setProperty("webdriver.edge.driver","C:\\Users\\moham\\Project\\selinum-test\\app\\src\\test\\resources\\msedgedriver.exe");
        webDriver=new EdgeDriver();
        webDriver.get("https://petclincqpros.herokuapp.com/");
      }

      @AfterClass
      public void afterTest(){
       webDriver.close();

      }

}
